# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        InscriptionBundle\Entity\User: sha512
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login

            logout:
                path:       fos_user_security_logout
                target:     /admin
            remember_me:
                secret: %secret%

    access_control:
                 - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
                 - { path: ^/admin, roles: ROLE_ADMIN }