<?php

namespace AppBundle\Repository;

/**
 * AcensiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcensiRepository extends \Doctrine\ORM\EntityRepository
{
}
