<?php

namespace AppBundle\Repository;

/**
 * HomePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomePageRepository extends \Doctrine\ORM\EntityRepository
{
}
