<?php

namespace AppBundle\Repository;

/**
 * Last_editionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Last_editionRepository extends \Doctrine\ORM\EntityRepository
{
}
