<?php

namespace AppBundle\Repository;

/**
 * PartnerPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerPageRepository extends \Doctrine\ORM\EntityRepository
{
}
