<?php

namespace AppBundle\Repository;

/**
 * Social_networkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Social_networkRepository extends \Doctrine\ORM\EntityRepository
{
}
