<?php

namespace AppBundle\Repository;

/**
 * StreamPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamPageRepository extends \Doctrine\ORM\EntityRepository
{
}
