<?php

namespace AppBundle\Repository;

/**
 * VisuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisuelRepository extends \Doctrine\ORM\EntityRepository
{
}
