<?php

namespace InscriptionBundle\Repository;

/**
 * Dev_cupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dev_cupRepository extends \Doctrine\ORM\EntityRepository
{
}
