<?php

namespace InscriptionBundle\Repository;

/**
 * game_soloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class game_soloRepository extends \Doctrine\ORM\EntityRepository
{
}
