<?php

namespace InscriptionBundle\Repository;

/**
 * game_multiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class game_multiRepository extends \Doctrine\ORM\EntityRepository
{
}
