<?php

namespace InscriptionBundle\Repository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionSoloRepository extends \Doctrine\ORM\EntityRepository
{
}
