<?php

namespace TournamentBundle\Repository;

/**
 * few_wordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class few_wordRepository extends \Doctrine\ORM\EntityRepository
{
}
