<?php

namespace TournamentBundle\Repository;

/**
 * PastilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastilleRepository extends \Doctrine\ORM\EntityRepository
{
}
